# julia/MinBoosters/Project.toml
name = "SL2CBoosters"
uuid = "2156dea3-675f-4838-9701-8878dc0e73c2"  # Generate a new UUID
authors = ["Kevin Rudolf Siebert <k.r.siebert@icloud.com>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
CMake = "631607c0-34d2-5d66-819e-eb0f9aa2061a"
HalfIntegers = "f0d1745a-41c9-11e9-1dd9-e5d34d218721"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.9"
HalfIntegers = "1"
CMake = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
